package org.kuali.rice.kew.api;
public interface WorkflowDocument {
    String getDocumentId();
    String getDocumentTypeName();
    String getTitle();
    org.kuali.rice.kew.api.document.DocumentStatus getStatus();
    String getInitiatorPrincipalId();
    org.joda.time.DateTime getDateCreated();
    org.joda.time.DateTime getDateLastModified();
    org.joda.time.DateTime getDateFinalized();
    boolean isInitiated();
    boolean isSaved();
    boolean isEnroute();
    boolean isProcessed();
    boolean isFinal();
    boolean isCanceled();
    boolean isDisapproved();
    boolean isApproved();
    boolean isRecalled();
    boolean isCompletionRequested();
    boolean isApprovalRequested();
    boolean isAcknowledgeRequested();
    boolean isFYIRequested();
    void approve(String annotation);
    void complete(String annotation);
    void route(String annotation);
    void save(String annotation);
    void cancel(String annotation);
    void disapprove(String annotation);
    void acknowledge(String annotation);
    void fyi();
    void blanketApprove(String annotation);
    void superUserBlanketApprove(String annotation);
    void superUserApprove(String annotation);
    java.util.Set<String> getNodeNames();
    org.kuali.rice.kew.api.document.DocumentStatus getDocumentStatus();
    String getApplicationDocumentStatus();
    void setApplicationDocumentStatus(String status);
    String getApplicationDocumentId();
    void setApplicationDocumentId(String id);
}
