package org.kuali.rice.core.api.config.property;

public interface Config {
    String getDailyEmailFirstDeliveryDate();
    String getWeeklyEmailFirstDeliveryDate();
    String getBaseWebServiceURL();
    String getBaseWebServiceWsdlPath();
    String getClientWSDLFullPathAndFileName();
    String getWebServicesConnectRetry();
    String getKEWBaseURL();
    String getKIMBaseURL();
    String getKRBaseURL();
    String getKENBaseURL();
    String getLog4jFileLocation();
    String getLog4jReloadInterval();
    String getTransactionTimeout();
    String getEmailConfigurationPath();
    String getRiceVersion();
    String getApplicationName();
    String getApplicationVersion();
    String getEnvironment();
    String getProductionEnvironmentCode();
    String getEDLConfigLocation();
    String getDefaultKewNoteClass();
    String getEmbeddedPluginLocation();
    Integer getRefreshRate();
    String getEndPointUrl();
    String getAlternateSpringFile();
    String getAlternateOJBFile();
    String getKeystoreAlias();
    String getKeystorePassword();
    String getKeystoreFile();
    String getDocumentLockTimeout();
    Boolean getEmailReminderLifecycleEnabled();
    Boolean getXmlPipelineLifeCycleEnabled();
    Boolean getDevMode();
    Boolean getBatchMode();
    Boolean getOutBoxOn();
    boolean isProductionEnvironment();
    java.util.Properties getProperties();
    String getProperty(String key);
    boolean getBooleanProperty(String key, boolean defaultValue);
    Boolean getBooleanProperty(String key);
    long getNumericProperty(String key, long defaultValue);
    Long getNumericProperty(String key);
    java.util.Map<String, String> getPropertiesWithPrefix(String prefix, boolean stripPrefix);
    java.util.Map<String, Object> getObjects();
    Object getObject(String key);
    void putProperties(java.util.Properties properties);
    void putProperty(String key, String value);
    void removeProperty(String key);
    void putObjects(java.util.Map<String, Object> objects);
    void putObject(String key, Object value);
    void removeObject(String key);
}
