kfs.datasource.username=kuldev
kfs.datasource.password=kuldev
kfs.datasource.url=jdbc:mysql://localhost:3306/kuldev?useSSL=false&characterEncoding=UTF-8
rice.datasource.url=${kfs.datasource.url}
rice.datasource.username=${kfs.datasource.username}
rice.datasource.password=${kfs.datasource.password}
kfs.datasource.validating.query=select 1
rice.datasource.validating.query=select 1
base.url=http://localhost:8080
environment=dev
app.context.name=kfs-web-dev
current.year=2026
