package org.kuali.rice.kns.web.struts.action;

public class KualiDocumentActionBase extends org.kuali.rice.kns.web.struts.action.KualiAction {
    public KualiDocumentActionBase() {}


    public org.apache.struts.action.ActionForward execute(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward docHandler(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward insertAdHocRoutePerson(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward deleteAdHocRoutePerson(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward insertAdHocRouteWorkgroup(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward deleteAdHocRouteWorkgroup(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward sendAdHocRequests(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward reload(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward save(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward delete(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward performRouteReport(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward route(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward blanketApprove(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward approve(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward disapprove(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward cancel(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward recall(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward close(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward fyi(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward acknowledge(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward supervisorFunctions(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward refresh(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward cancelBOAttachment(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward downloadBOAttachment(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward insertBONote(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward deleteBONote(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward sendNoteWorkflowNotification(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward promptBeforeValidation(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward promptBeforeValidation(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3, java.lang.String p4) throws java.lang.Exception { return null; }
    public org.kuali.rice.kns.service.BusinessObjectMetaDataService getBusinessObjectMetaDataService() { return null; }
    public javax.persistence.EntityManagerFactory getEntityManagerFactory() { return null; }
    public org.apache.struts.action.ActionForward hideAllTabs(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward showAllTabs(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward toggleTab(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    public org.apache.struts.action.ActionForward takeSuperUserActions(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) { return null; }
    public org.apache.struts.action.ActionForward superUserDisapprove(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) { return null; }
    public org.apache.struts.action.ActionForward superUserApprove(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) { return null; }
    public org.apache.struts.action.ActionForward complete(org.apache.struts.action.ActionMapping p0, org.apache.struts.action.ActionForm p1, javax.servlet.http.HttpServletRequest p2, javax.servlet.http.HttpServletResponse p3) throws java.lang.Exception { return null; }
    protected void loadDocument(org.kuali.rice.kns.web.struts.form.KualiDocumentFormBase form) throws org.kuali.rice.kew.api.exception.WorkflowException {}
    protected org.apache.struts.action.ActionForward performQuestionWithoutInput(org.apache.struts.action.ActionMapping mapping, org.apache.struts.action.ActionForm form, javax.servlet.http.HttpServletRequest request, javax.servlet.http.HttpServletResponse response, String questionId, String questionText, String questionType, String caller, String context) throws Exception { return null; }
    protected Object addObjectWithGeneratedKey(org.apache.struts.action.ActionForm form) { return null; }
}
